import { Metadata } from "next";
import localFont from "next/font/local";
import { getConpanyInformations } from "./crud";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const companyInformation = await getConpanyInformations();

export const metadata: Metadata = {
  title: companyInformation?.name?.english || "Default Title",
  description: "Generated by create next app",
  icons: {
    icon: companyInformation?.logo || "/default-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <title>{companyInformation?.name?.english || "Default Title"}</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
